-- AlterTable
ALTER TABLE "BrokenItem" ALTER COLUMN "dateBroke" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ExportedItem" ALTER COLUMN "dateExported" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Inventory" ALTER COLUMN "dateReceived" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "List" ALTER COLUMN "dateInuse" SET DEFAULT CURRENT_TIMESTAMP;
